### ISSUE TITLE
Unable to understand README

### ISSUE THREAD

**Issue by Compro-Prasad** [myuhe/org-gcal.el#118]
Can you explain this part from the `README`?

> OAuth token expired in 3600 seconds, You should refresh token on a regular basis.

**Comment by creichert** [comment]
Every once and a while, when you fetch or sync your org calendar w/
Google Calendar, you will get a minibar notification with a link in that
you need to open in your browser, do the captcha, and enter the token
back into the minibuffer.

The best way to understand the README is to just install and use
org-gcal. Did you get it to work?

**Comment by Compro-Prasad** [comment]
Yes it works fine. Glad the steps were almost perfect. Google keeps moving things frequently which isn't helpful. Or may be its just me.
It would be better to describe instead of specifying a one liner. It isn't twitter, so what is the limiting factor?!

**Comment by telotortium** [comment]
Hi everyone! This repository is obsolete - the actively developed fork is now https://github.com/kidd/org-gcal.el, which is also the "org-gcal.el" on MELPA (see [#115](https://github.com/myuhe/org-gcal.el/issues/115)). I'm one of the maintainers of https://github.com/kidd/org-gcal.el. I can't directly close issues or PRs on this repo, but please download https://github.com/kidd/org-gcal.el and see if your issue or PR is still applicable. If so, open an issue or PR on https://github.com/kidd/org-gcal.el. In any case, you should close your issue or PR in this repo.
