### ISSUE TITLE
One of my GCal calendars is in UTC time, comes down as UTC but need it local

### ISSUE THREAD

**Issue by christoofar** [myuhe/org-gcal.el#120]
Have a small issue with my work calendar which I import from Office365 into Google Calendar (so I can see my Outlook calendar events in emacs, I expose it as a Google Calendar)...

The timezone is 00:00UTC.   So when it's written to disk in .org mode it is not translated to local time.

I'm in USA Eastern Standard Time as of right now (GMT-5).

Here's what it looks like in Google settings (where I've imported the calendar from Office 365)
![image](https://user-images.githubusercontent.com/5059144/48029516-5bc87d80-e11c-11e8-9360-f3d9ee5567e9.png)

Here's an appointment which is in my local time zone (visible on Mac Calendar)
![image](https://user-images.githubusercontent.com/5059144/48029628-a649fa00-e11c-11e8-8b18-2aa929fc4091.png)

Ok, so far so good.. this is the correct time of that appointment.  Now here's what it looks like in org-gcal after syncing:

![image](https://user-images.githubusercontent.com/5059144/48029694-d8f3f280-e11c-11e8-8122-4c722cc15bf2.png)

This is wrong... this is what the appointment is in UTC time (as if I were in the UTC time zone), not converted to local.  IOW this is a morning appointment but because there was no conversion it's showing up at the end of my work day.

It wrote this to the .org file not knowing that the .ICS is set to UTC 00:00.

And of course it's wrong in agenda as well:

![image](https://user-images.githubusercontent.com/5059144/48029773-148ebc80-e11d-11e8-85c5-76d8f16c057e.png)

Any ideas on a fix?

**Comment by christoofar** [comment]
This is an absolute complete hack but I went ahead and added a header to the call to fetch the calendar.   Google accepts time zone names "America/New_York" for instance.   This allowed me to get around the problem for now.

![image](https://user-images.githubusercontent.com/5059144/48030980-b532ab80-e120-11e8-9239-e220aa3e9cd4.png)

**Comment by bobberb** [comment]
The community left this repo for

https://github.com/kidd/org-gcal.el/

And that repo is what MELPA currently references

**Comment by telotortium** [comment]
Hi everyone! This repository is obsolete - the actively developed fork is now https://github.com/kidd/org-gcal.el, which is also the "org-gcal.el" on MELPA (see [#115](https://github.com/myuhe/org-gcal.el/issues/115)). I'm one of the maintainers of https://github.com/kidd/org-gcal.el. I can't directly close issues or PRs on this repo, but please download https://github.com/kidd/org-gcal.el and see if your issue or PR is still applicable. If so, open an issue or PR on https://github.com/kidd/org-gcal.el. In any case, you should close your issue or PR in this repo.
