### ISSUE TITLE
org file automatically re-arrange when using org-gcal-post-at-point

### ISSUE THREAD

**Issue by irbin-b** [myuhe/org-gcal.el#125]
Hi,
I have a .org file where I save all my events. This file is syncing with my google account. It works fine, but sometimes when I execute the org-gcal-post-at-point command my .org file automatically re-arrange all my events, and I have to arrange all of them manually once again.

The message that appears is:
OAuth token expired. Now trying to refresh-token

**Comment by telotortium** [comment]
File your bug on https://github.com/kidd/org-gcal.el. That fork is the one
that's being maintained now.

**Comment by irbin-b** [comment]
Ops! I have moved this issue now. Thanks.
