### ISSUE TITLE
issues pushing entries to google calendar

### ISSUE THREAD

**Issue by MarinosK** [myuhe/org-gcal.el#126]
Hello, 
my setup is absolutely OK insofar as fetching entries from google is concerned. I have problem pushing, tho - I'm not entirely sure if that's because I fail to understand what exactly to do or due to some bug. 

with something like that:

```
* testing local
<2020-05-09 Sat 10:00-11:00>
```

after `org-gcal-post-at-point` I get `Wrong type argument: fixnump, nil`

with this

```
* testing local
:org-gcal:
<2020-05-09 Sat 10:00-11:00>
:END:
```
I get this error

```
(error http 404)

Status code: 404
(error http 404)

deferred error : (error "Got error 404: (error http 404)")
user-error: Minibuffer window is not active
```

with something like that

```
* testing local
:PROPERTIES:
:ETag:     ""
:calendar-id: MY_CAL_ID
:ID:       MY_ID
:END:
:org-gcal:
<2020-05-09 Sat 10:00-11:00>
:END:
```
I get 

```
ETag stale - will overwrite this entry with event from server.
Received HTTP 412
ETag stale - will overwrite this entry with event from server.
```
and then the entire entry is in my file is swapped another one that already exists in google cal.

This does not seem to be the intended behaviour to me. 

Thanks in advance for the help

**Comment by telotortium** [comment]
Please file this issue on kidd/org-gcal.el - that is where development is taking place.

**Comment by MarinosK** [comment]
done, I'm closing this down
