### ISSUE TITLE
deferred error on org-gcal-sync and org-gcal-fetch

### ISSUE THREAD

**Issue by erikc96** [myuhe/org-gcal.el#128]
deferred error : (wrong-type-argument hash-table-p (("my-email" (NUMBER NUMBER NUMBER 0) "SOME SORT OF SECRET)))

Hi, I'm getting the above error when running either org-gcal-sync and org-gcal-fetch (I removed some details from it in case they were PII.)

**Comment by sraghavendran** [comment]
I am having the same error. Did you manage to fix this? Would appreciate any pointers.

**Comment by telotortium** [comment]
Hi, this repo is obsolete. Please try https://github.com/kidd/org-gcal.el
