### ISSUE TITLE
Escape hash sign

### ISSUE THREAD

**Issue by bitozoid** [myuhe/org-gcal.el#137]
I tried to make it work with my birthdays calendar (from google contacts):

```
addressbook#contacts@group.v.calendar.google.com
```

It did not work until I encoded the `#` sign to `%23`.

I think this could be done by the package.

**Comment by telotortium** [comment]
Please test this on https://github.com/kidd/org-gcal.el - this package is obsolete.

**Comment by bitozoid** [comment]
My fault.

https://github.com/kidd/org-gcal.el/issues/177

Thanks a lot.
