### ISSUE TITLE
`org-gcal-fetch` fails

### ISSUE THREAD

**Issue by flexibeast** [myuhe/org-gcal.el#16]
Running `org-gcal-fetch` fails in the function `org-gcal--archive-old-event`. More specifically, it fails on the line `(goto-char (cdr (org-gcal--timestamp-successor)))` when the value of `org-gcal--timestamp-successor` is `nil`, returning `(wrong-type-argument integer-or-marker-p nil)`.

**Comment by sje30** [comment]
I had this problem too on mac.  I think the problem was that my version of Emacs (on mac) did not compiled with gnutls support.  This was verified by
```
(gnutls-available-p)
```
returning `nil` in my Emacs.  Switching to a newer version of Emacs had the fortunate side effect of also being compiled with gnutls.
