### ISSUE TITLE
Why do org-gcal-fetch and org-gcal-post-at-point execute kill-buffer after those?

### ISSUE THREAD

**Issue by kenbeese** [myuhe/org-gcal.el#24]
When I want to add or edit two schedules, I do a following process.

1. open a file
2. add or edit a schedule
3. execute `M-x org-gcal-post-at-point`.
4. reopen the file.
5. add or edit the other schedule.
6. execute `M-x org-gcal-post-at-point`.

I want to remove the process 4.

**Comment by myuhe** [comment]
Merge your commit daa906c5f0bcf70a645445c978f7d55002e24670.
This commit solve #24.
Thanks.
