### ISSUE TITLE
Can I delete a event?

### ISSUE THREAD

**Issue by sollidsnake** [myuhe/org-gcal.el#40]
I delete the calendar event in the org file, and run `org-gcal-sync`, but this brings back the deleted event. Is this how it's suppose to behave? Isn't it possible to delete an event?

**Comment by erikmd** [comment]
Hi Jesse,

Le samedi 19 septembre 2015 à 12:56 -0700, Jesse Nazario a écrit :

> I delete the calendar event in the org file, and run
> `org-gcal-sync`, but this brings back the deleted event.
> Is this how it's suppose to behave?

Yes, the implementation of the (org-gcal-sync) function does not
currently provide such a "delete" feature.

> Isn't it possible to delete an event?

Actually, the current possibility for deleting one or several events
is to log into Google Calendar, to perform the deletion over there,
and finally to call (org-gcal-fetch).

Note: there is already a facility to quickly open the Google Calendar
page corresponding to a given org-gcal.el event: to use it you have to
unfold the event and its :PROPERTIES: list in Emacs with the <TAB> key
and click on the :LINK:
[[https://www.google.com/calendar/event?eid=...][Go to gcal web page]]

Anyway: if need be, it should be feasible to implement a function
named (org-gcal-delete-at-point) or so, to delete an event in Gcal
using Emacs directly; and this function could also archive the given
event (in the *.org_archive file) while deleting it in Gcal...
Afterwards, this feature should indeed be triggered by (org-gcal-sync)
itself, while I suspect that the deletion-detection algorithm would be
slightly more involved (e.g., to cope with reordering of events...)

Best regards,

Erik MD

**Comment by sollidsnake** [comment]
I see. Thanks for the clarifying answer. Please feel free to close this issue if you wish.

**Comment by erikmd** [comment]
Hi,

Le mercredi 23 septembre 2015 à 04:12 -0700, Jesse Nazario a écrit :
> I see. Thanks for the clarifying answer. Please feel free to close
> this issue if you wish.

OK; maybe it's better to keep it open until the feature is implemented
(otherwise, only you or the repo owner could close the issue anyway).

Best regards.

**Comment by alphapapa** [comment]
It seems like this is the kind of basic feature that should be necessary for the package to be considered feature complete.  Otherwise it should be very prominently described as a one-way sync tool.

**Comment by dsharoh** [comment]
A little work around I use to delete events within the org file associated with the calendar is to predate the event I want to remove. For example, if there is an event for <2016 01-04>, changing it to <2015 01-04> and then syncing removes the event from both the calendar and the org doc. Maybe this will work for anyone who has this problem too.

**Comment by eggcaker** [comment]
+1

**Comment by felipeochoa** [comment]
I don't have time to implement this, but it doesn't look tremendously hard to write an `(org-gcal-delete-event calendar-id event-id)` function: https://developers.google.com/google-apps/calendar/v3/reference/events/delete. From there you'd just need to use `org-element-at-point` to grab the event ID. Not sure how you grab the calendar ID, but presumable `org-gcal` has it stored somewhere?
