### ISSUE TITLE
Update events rather than overwrite them

### ISSUE THREAD

**Issue by danlamanna** [myuhe/org-gcal.el#42]
I think this would involve updating the headings based on the unique ID gcal gives back, this way the user can add notes beneath each calendar event and have them retained. This would have to create special logic for updating, removing the calls to `erase-buffer`.

**Comment by myuhe** [comment]
Thank you for your opinion, but I can't understand it.
Show how to reproduce it.

**Comment by danlamanna** [comment]
It's not a bug, it's a feature request.

For example:
```org-gcal-fetch``` results in:
```
* Event 1
* Event 2
* Event 3
```

I change some things so the file looks like:
```
* Event 1
** This went really well
* Event 2
* Event 3
```

Running ```org-gcal-fetch``` again, results in the original file - removing my "This went really well" note.

**Comment by nikclayton** [comment]
+1. I was hoping to be able to use org-gcal and org-clock-in to:

- Not have to retype event titles from calendar in to org files
- Use org-clock-in to record the actual time spent in a meeting (which is not always the same as the allocated time).

But org-gcal erases the file, so the :LOGBOOK: entries from org-clock-in are being erased.

**Comment by telotortium** [comment]
Hi everyone! This repository is obsolete - the actively developed fork is now https://github.com/kidd/org-gcal.el, which is also the "org-gcal.el" on MELPA (see [#115](https://github.com/myuhe/org-gcal.el/issues/115)). I'm one of the maintainers of https://github.com/kidd/org-gcal.el. I can't directly close issues or PRs on this repo, but please download https://github.com/kidd/org-gcal.el and see if your issue or PR is still applicable. If so, open an issue or PR on https://github.com/kidd/org-gcal.el. In any case, you should close your issue or PR in this repo.
