### ISSUE TITLE
Blocking issue: (org-gcal-sync) fails to fetch from Gcal because (eq status nil) holds

### ISSUE THREAD

**Issue by erikmd** [myuhe/org-gcal.el#44]
With the current master version of `org-gcal.el`, fetch, post and sync do not work anymore since last week:

It might be due to the way `org-gcal.el` handle *tokens* (combined with a slight change in Gcal)... Indeed at each fetch attempt, I am asked to "Enter the code your browser displayed:", which successfully opens the corresponding window in my browser. Afterwards:
* old events are archived,
* but the sync with Gcal fails with message "Could not contact remote service. Please check your network connectivity." (so this means that the request led to the `(eq status nil)` case!)
* and the file `.org-gcal-token` now contains `(:token nil :elem nil)` ...

**Comment by erikmd** [comment]
Hi,

Thanks to the commits in #45 I was able to debug this issue, which was due to (a config update of) the `curl` backend on Ubuntu, raising the emacs message:
```
Got error: (error . "exited abnormally with code 77
")
```
More precisely:
```bash
$ man curl | grep 77
       77     Problem with reading the SSL CA cert (path? access rights?).
```
And the fix proposed in http://askubuntu.com/questions/646594/how-to-fix-ca-cert-issues-with-curl-in-ubuntu-14-04 was successful on my system.

To sum up, I just needed to create a text file named `~/.curlrc` with contents
```
cacert=/etc/ssl/certs/ca-certificates.crt
```
and `org-gcal.el` is working again for me.

Best regards.

**Comment by maikol-solis** [comment]
I had the very same issue and I could solve the problem with the @erikmd solution.

However, emacs do not open the link generated by `org-gcal` when I try to sync with Calendar, and of course I can't enter any code. 

I have this in my Messages buffer. 

```
Got error: (error http 404) [2 times]
(error http 404)

(error http 404)

Got error: (error http 400)
```

Thanks for the help.
