### ISSUE TITLE
Encoding problem with new request.el

### ISSUE THREAD

**Issue by elandx** [myuhe/org-gcal.el#48]
Thank You very much for the great package! I really like it. 
But after update of ELPA's "request" I constantly get a popped up orgbuffer with my google calendar filled up with "\342\" etc. and message "Select one of the safe coding systems listed below etc." when I issued "org-gcal-fetch".
For now I cloned tkf/emacs-request and happily use them.  Interestingly the ELPA's version is not tkf's but abingham/emacs-request. The main difference is that latter use "cl-defun" i.o. "defun". Thanks in advance :)

**Comment by lurdan** [comment]
MELPA had (forked and) switched request's upstream because of tkf's MIA.

> The main difference is that latter use "cl-defun" i.o. "defun".

@syohex Don't you have any ideas about this?

**Comment by syohex** [comment]
Sorry I don't understand this package well. I'll check later.

**Comment by syohex** [comment]
How about this patch ?

```patch
diff --git a/org-gcal.el b/org-gcal.el
index 6078804..b846401 100644
--- a/org-gcal.el
+++ b/org-gcal.el
@@ -424,7 +424,8 @@ It returns the code provided by the service."
     (re-search-forward "^{" nil t)
     (delete-region (point-min) (1- (point)))
     (goto-char (point-min))
-    (json-read)))
+    (json-read-from-string
+     (decode-coding-string (buffer-string) 'utf-8))))
 
 (defun org-gcal--get-refresh-token ()
   (if org-gcal-token-plist
```

**Comment by lurdan** [comment]
Splendid, Thanks!

I've confirmed that redefining the function make fetching work again.
