### ISSUE TITLE
Duplication of events with location when using `org-gcal-sync`

### ISSUE THREAD

**Issue by alexkehayias** [myuhe/org-gcal.el#49]
When using `org-gcal-sync` I noticed that duplication of events starts to occur on events that have a location field (specified when using iCal that is synced with Google Calendar). Subsequent duplicate events are missing the location field, but all have unique IDs.

**Comment by gciolli** [comment]
See #85 (not sure whether it helps)

**Comment by phrxmd** [comment]
Can you check whether https://github.com/myuhe/org-gcal.el/pull/122 fixes this? It could be that a second property drawer was generated that contained the ID, but not the location field.

**Comment by alexkehayias** [comment]
Hi thanks for bumping, I just set it up again and I'm not seeing duplicates, but it might not be a good repro. Closing this out.
