### ISSUE TITLE
deferred error : (text-read-only)

### ISSUE THREAD

**Issue by eggcaker** [myuhe/org-gcal.el#50]
after i ran `org-gcal-sync` or `org-gcal-fetch` command, i got error 

```
Saving file /Users/myname/.emacs.d/.cache/org-gcal/org.png...
deferred error : (text-read-only)
```

did I missing some configuration?  but seems the task synced...

**Comment by guedes** [comment]
Same here.

**Comment by mashdot** [comment]
Yup me too.

**Comment by shackra** [comment]
me too.

**Comment by timoc** [comment]
Same here. org-gcal--notify is broken. Found this fix to to replace it. put it after you have loaded org-gcal
```
(defun new/org-gcal--notify (title mes)
    (message "org-gcal::%s - %s" title mes))
  (fset 'org-gcal--notify 'new/org-gcal-notify))
```
all this does is paper over the cracks, I personally would prefer having this message buffer option as well as system notifications

**Comment by kevzettler** [comment]
Still a problem. @timoc 's suggestion worked for me

**Comment by telotortium** [comment]
Hi everyone! This repository is obsolete - the actively developed fork is now https://github.com/kidd/org-gcal.el, which is also the "org-gcal.el" on MELPA (see [#115](https://github.com/myuhe/org-gcal.el/issues/115)). I'm one of the maintainers of https://github.com/kidd/org-gcal.el. I can't directly close issues or PRs on this repo, but please download https://github.com/kidd/org-gcal.el and see if your issue or PR is still applicable. If so, open an issue or PR on https://github.com/kidd/org-gcal.el. In any case, you should close your issue or PR in this repo.
