### ISSUE TITLE
Template for new Appointment

### ISSUE THREAD

**Issue by der-Daniel** [myuhe/org-gcal.el#59]
Hello,

thanks for this great package, I really appreciate the effort.
I am currently trying to get a template running, that includes some basic field like `Subject` and `Date`.

I am new to the template thing. On [here](http://orgmode.org/manual/Capture-templates.html) I found an example, but I cannot transfer it to the way I want it.

```
     (setq org-capture-templates
      '(("t" "Todo" entry (file+headline "~/org/gtd.org" "Tasks")
             "* TODO %?\n  %i\n  %a")
        ("j" "Journal" entry (file+datetree "~/org/journal.org")
             "* %?\nEntered on %U\n  %i\n  %a")))
```

Can someone help?

Cheers
Daniel

**Comment by tshu-w** [comment]
My simply template is, hope help:
```
  (setq org-capture-templates
       '(("t" "Todo" entry (file+headline org-agenda-file-gtd "Tasks")
            "* TODO %?\n  %i\n")
          ("a" "Appointment" entry (file org-agenda-file-gcal)
           "* %?\n  %^T\n\n")))
```
