### ISSUE TITLE
Multiple org files to one calendar?

### ISSUE THREAD

**Issue by sje30** [myuhe/org-gcal.el#67]
Hi,
I previously used org-caldav (until the google support was dropped).  In that, you could map multiple org files into one google calendar.  Is that possible with org-gcal?  e.g. would something like the following be okay?

```
(setq org-gcal-file-alist '(("your-mail@gmail.com" .  "~/schedule.org")
			    ("your-mail@gmail.com" .  "~/work.org")
			    ("your-mail@gmail.com" .  "~/office.org")))
```

**Comment by myuhe** [comment]
Yes, Multiple files is supported.
