### ISSUE TITLE
Many unsaved org.png buffers on org-gcal-fetch

### ISSUE THREAD

**Issue by nixmaniack** [myuhe/org-gcal.el#74]
```
Saving file /Users/nixmaniack/.emacs.d/org-gcal/org.png...
deferred error : (text-read-only)
Type C-c C-c or C-c C-x to view the image as text or hex.
```
Above message is repeated many times in `*Messages*` buffer.

![image](https://cloud.githubusercontent.com/assets/542810/21061168/31bdfae4-be71-11e6-9c1b-d7d14405c985.png)

**Comment by kamidon** [comment]
Put this image: https://raw.githubusercontent.com/myuhe/org-gcal.el/master/org.png
in `~/.emacs.d/org-gcai/org.png` and the problem will do away. I haven't spent the time to figure out why it is trying to download this image and failing whenever it logs a message about what it is doing, but this will fix it.

If someone wants to look in more detail, the one hint I can give is that it might have something to do with the downloaded png being in a buffer in Imagemagick mode.

**Comment by nixmaniack** [comment]
> Put this image: https://raw.githubusercontent.com/myuhe/org-gcal.el/master/org.png
in ~/.emacs.d/org-gcai/org.png and the problem will do away. 

Yes. I have done that and I don't see such buffers created.

**Comment by nixmaniack** [comment]
Closing as `org-gcal` is no more maintained in this repo.
