### ISSUE TITLE
Got error: (error http 400)

### ISSUE THREAD

**Issue by srustamo** [myuhe/org-gcal.el#82]
Set up everything as per the readme, get Got error: (error http 400). Toggling debug on error does not give any trace.

**Comment by badkey** [comment]
Same here after inputting the token from google. I run
‘org-gcal-20161115.357 with GNU Emacs 25.1.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.5) of 2017-01-01, modified by Debian.

**Comment by fth86** [comment]
same here.

org-gcal-20161115.357
emacs 26.0.50.3

**Comment by kevzettler** [comment]
Same thing here `*Messages*` showing:
```
Got error: (error http 400)
Contacting host: raw.githubusercontent.com:443
Type C-c C-c to view the image as text.
Saving file /Users/kev/.emacs.d/org-gcal/org.png...
deferred error : (text-read-only)
```

```
org-gcal 20161115.357
GNU Emacs 25.1.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2016-09-20
```

I did recently have this working no major updates but moving my credentials to a `.gpg` file

**Comment by darosio** [comment]
emacs 25.1.1 and org-gcal 20161115.357
same (error http 400) for fetch or sync operation
and errot http 401for refresh-token operation.

**Comment by darosio** [comment]
I managed to download once from google calendar into org file by:
1. deleting .emacs.d/org-gcal/.org-gcal-token
2. reinstalling from elpa org-gcal (probably not necessary)
3. org-gcal-fetch (getting new auth from google)
4. org-gcal-refresh-token
5. org-gcal-fetch

**Comment by dominic998** [comment]
I had this problem. To fix I evaluated (C-x C-e, just in *scratch* buffer):
(org-gcal-request-token)

Which opened a google page in my browser, I signed in and entered the token I got on the page into the minibuffer as instructed. I hope that works for other people as well.

Perhaps org-gcal.el is not correctly recognising when it needs to ask google for authorisation again.

EDIT: Just FYI, previous to finding this fix, in my .emacs.d/org-gcal/.org-gcal-token the value of :access_token was always "nil". After doing (org-gcal-request-token) it got assigned a string.

**Comment by srustamo** [comment]
@dominic998 
That worked, thanks.

**Comment by ygol** [comment]
following @dominic998 receipt, I could get it to work last week but since few days it doesn't work anymore. I tried deleting .emacs.d/org-gcal/.org-gcal-token and then evaluating (org-gcal-request-token) and also tried several times over these days to use org-gcal-refresh-token but I get each time an http error 401.
Anyone else has this problem?

**Comment by phrxmd** [comment]
Worked for me too, thanks.

**Comment by felipelalli** [comment]
> I managed to download once from google calendar into org file by:
> 
> 1. deleting .emacs.d/org-gcal/.org-gcal-token
> 2. reinstalling from elpa org-gcal (probably not necessary)
> 3. org-gcal-fetch (getting new auth from google)
> 4. org-gcal-refresh-token
> 5. org-gcal-fetch

Thank you.
