### ISSUE TITLE
go to the corresponding line in .org file from agenda view by typing TAB

### ISSUE THREAD

**Issue by QikeLi** [myuhe/org-gcal.el#90]
Hi,

This is an awesome package! I have a problem with going to the corresponding line in my .org file (the one in org-gcal-file-alist) from agenda view by typing TAB. Once I type TAB in the agenda view, it will take me to the very last line in my .org file, not the line that corresponds to the event in my agenda view. However, for other events that in my main .org file (not in org-gcal-file-alist), it works fine. Would you please let me know if there is something wrong in my configuration?

Thank you!

**Comment by SakuAura** [comment]
Also affected by this.

**Comment by SakuAura** [comment]
Fixed this by removing the following from my .emacs:
(add-hook 'org-agenda-mode-hook (lambda () (org-gcal-sync) ))

I had adapted my setup from http://cestlaz.github.io/posts/using-emacs-26-gcal

**Comment by QikeLi** [comment]
@SakuAura Thank you! Your solution worked for me as well.
